(add-to-list 'load-path (locate-user-emacs-file "el-get/el-get"))
(unless (require 'el-get nil 'noerror)
  (with-current-buffer
      (url-retrieve-synchronously
       "https://raw.githubusercontent.com/dimitri/el-get/master/el-get-install.el")
    (goto-char (point-max))
    (eval-print-last-sexp)))

(add-to-list 'el-get-recipe-path (locate-user-emacs-file "el-get-recipes"))

(el-get-bundle use-package)
(el-get-bundle color-theme)
(el-get-bundle ace-jump-mode)
(el-get-bundle auto-complete)
(el-get-bundle autopair)
(el-get-bundle expand-region)
(el-get-bundle flycheck)
(el-get-bundle git-gutter)
(el-get-bundle open-junk-file)
(el-get-bundle popwin)
(el-get-bundle redo+)
(el-get-bundle sequential-command)
(el-get-bundle yasnippet)

(el-get-bundle helm)
(el-get-bundle helm-ls-git)
(el-get-bundle helm-gtags)
(el-get-bundle helm-ag)

(el-get-bundle auto-async-byte-compile)
(el-get-bundle paredit)
(el-get-bundle lispxmp)
(el-get-bundle php-mode)
(el-get-bundle php-eldoc)
(el-get-bundle ruby-mode)
(el-get-bundle ruby-end)
(el-get-bundle rinari)
(el-get-bundle rhtml-mode)
(el-get-bundle web-mode)
(el-get-bundle go-mode)
(el-get-bundle markdown-mode)
(el-get-bundle scss-mode)
(el-get-bundle yaml-mode)
(el-get-bundle elixir)
(el-get-bundle alchemist)
